Slight change to docker-compose detached commands
Hit an error with
```sh
% docker-compose up db -d
ERROR: No such service: -d
```
but
`docker-compose up -d db` works fine